### ISSUE TITLE
Build a mounting board

### ISSUE THREAD

**Issue by amcewen** [mcqn/my-babys-got-led#7]
Given ATX power supplies have a standard set of mounting points, we could laser-cut a nice board that mounts to the power supply and then provides suitable mounting points for the PCB, to keep everything together more neatly.

**Comment by arthurrowland** [comment]
Given we've seen that there is quite a lot of variation in ATX mounting, shall we adapt this issue to be just for mounting the board itself, and the user can adapt to their own supply and situation?

**Comment by arthurrowland** [comment]
I prepared this one-side board with two layers of 4mm MDF and M3x12 bolts. Would need etching to be useful. It's quite satisfying to hold and for casual applications the molex cable works fairly was as a stand to hold it at a useful angle. Don't love it, but is quite inexpensive to produce.

![IMG_20210614_170759425_1.jpg](https://user-images.githubusercontent.com/78351702/121924035-70893b00-cd33-11eb-9ff1-52d6ce8ea8be.jpg)

**Comment by arthurrowland** [comment]
Following an in-person discussion with @amcewen, I have been looking at the many PSU mounting patterns to scope out how many we might want to draw up, if any, beyond the 'standard' ATX mounting pattern.

Here's a really good summary of the different types of ATX power supplies, with the mounting patterns and external dimensions clearly visible:
http://www.evercase.co.uk/index.php?route=information/information&information_id=7

Here are the most common power supplies stacked, with an adaptor plate on the top SFU-type PSU.

![Three power supplies stacked, showing the different sizes and mounting patterns](https://user-images.githubusercontent.com/78351702/122771290-2f96a680-d29e-11eb-9b6c-6d9201f74838.png)

Here's a drawing for the cutout for SFX type PSUs found [here](https://www.overclock.net/threads/official-usff-sff-club.1300645/page-76):

![Specification for SFX panel cutout: (From the SFX12V Power Supply Design Guide, Version 2.0, Appenix C)](https://user-images.githubusercontent.com/78351702/122771710-95832e00-d29e-11eb-9250-32e657b12a98.png)

and here's the ATX one while we're at it, since it's not already linked in this issue:

![Specification for ATX PSU mounting hole placement: (From the ATX Power Supply Design Guide, Version 2.2)](https://user-images.githubusercontent.com/78351702/122771920-c8c5bd00-d29e-11eb-846b-c0fd39523b7b.png)

- Option 1: No mcqn support for SFX type
- Option 2: Design mounting plate with both sets of holes
- Option 3: Supply separate mounting plate for SFX
- Option 4: Supply adaptor plate for SFX to ATX - for example [£4 on ebay](https://www.ebay.co.uk/itm/154474553329) and [£2 on alibaba](https://www.aliexpress.com/item/1005002011841397.html)
- Option 5: Flag mounting issues and link people to adaptor plates <- most pragmatic option in my view

Next steps are to update the small board protector to become a sandwich-style case and add some simple outline labels, and update the PSU panel mount version with the latest, larger, revision of My Baby's Got LED.

**Comment by arthurrowland** [comment]
I have [renamed](https://github.com/mcqn/my-babys-got-led/commit/a32d96c2b49a5abdc0e383e5d23d10f2a5657efc) the ATX PS2 mounting board files ([twice](https://github.com/mcqn/my-babys-got-led/commit/b23c36c1570613539b88990fc99c7ff27c7890fe)) and included the design files for the following enclosure (rough prototype from scavenged acrylic, but dimensions are correct).

![_1010535](https://user-images.githubusercontent.com/78351702/125487483-753dc3e4-24fd-458c-97aa-ce3e288c549f.JPG)

It uses 20mm standoffs on the molex side and 10mm standoffs on the LED/status light side.

The new file names distinguish between rev1 and rev2 my baby's got LED boards and the PSU mounting patterns (where needed).

**Comment by arthurrowland** [comment]
After tidying up the files and confirming the fit by laser cutting them from 4mm MDF, I have [pushed a commit](https://github.com/mcqn/my-babys-got-led/commit/bdcdba95ba357ee028c69f880b48041155dd211b) with the mounting plate design files as SVG - including some text about what it is and what other components are needed- as well as as DXF with just the cutting lines ready for laser cutting.

Following an offline conversation about version control with @amcewen I have removed both the files and references to mounting plates for rev1 boards (the previous, smaller version) and anyone seeking the plate for the older board can [find it in the git history](https://github.com/mcqn/my-babys-got-led/commit/5b1159bde673399abf77f410be769da8bd5e364a#diff-6e8da356a6228e4d975e2ca76306ad6f771635e9151326be48942b9fde45de1c).

Regarding the SFX-type mounts, I think we've invested enough time into mounting plate options for now so opting for option 1: no mcqn support for SFX type. For now we will assume any PSU we supply with a mounting plate (most likely as part of a kit) will use a PS2 supply.
